version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    # The final line of arguments are workarounds for the fact that we don't
    # have dummy data working yet, so don't worry about exactly what they're
    # doing.
    run: databuilder:v0
      generate-dataset analysis/dataset_definition.py --output output/dataset.csv
      --dsn dummy_data --query-engine csv --backend databuilder.backends.base.DefaultBackend
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv
